;
; File generated by cc65 v 2.18 - Git ece63f0
;
	.fopt		compiler,"cc65 v 2.18 - Git ece63f0"
	.setcpu		"65816"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "kernel/src/main.c", 728, 1687606231
	.dbg		file, "kernel/cc65/include/mmu.h", 622, 1685851288
	.dbg		file, "kernel/src/globals.h", 109, 1686797992
	.dbg		file, "kernel/src/window.h", 2125, 1686886826
	.dbg		file, "kernel/src/conio.h", 530, 1687332411
	.dbg		file, "kernel/src/string.h", 242, 1687708971
	.forceimport	__STARTUP__
	.dbg		sym, "cls", "00", extern, "_cls"
	.dbg		sym, "cputc", "00", extern, "_cputc"
	.dbg		sym, "cputs", "00", extern, "_cputs"
	.dbg		sym, "cgetc", "00", extern, "_cgetc"
	.dbg		sym, "cbkspc", "00", extern, "_cbkspc"
	.dbg		sym, "strlen", "00", extern, "_strlen"
	.dbg		sym, "strcatc", "00", extern, "_strcatc"
	.dbg		sym, "strcmp", "00", extern, "_strcmp"
	.dbg		sym, "strdelc", "00", extern, "_strdelc"
	.import		_cls
	.import		_cputc
	.import		_cputs
	.import		_cgetc
	.import		_cbkspc
	.import		_strlen
	.import		_strcatc
	.import		_strcmp
	.import		_strdelc
	.export		_main

.segment	"RODATA"

L0029:
	.byte	$63,$6F,$6D,$6D,$61,$6E,$64,$20,$6E,$6F,$74,$20,$66,$6F,$75,$6E
	.byte	$64,$0A,$00
L0004:
	.byte	$48,$65,$6C,$6C,$6F,$72,$6C,$64,$21,$0A,$00
L0023:
	.byte	$63,$6C,$73,$00

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

	.dbg	func, "main", "00", extern, "_main"
	.dbg	sym, "i", "00", auto, -1
	.dbg	sym, "c", "00", auto, -2
	.dbg	sym, "input", "00", auto, -130

.segment	"CODE"

	.dbg	line, "kernel/src/main.c", 12
	ldy     #$82
	jsr     subysp
	lda     #<(L0004)
	ldx     #>(L0004)
	jsr     _cputs
	.dbg	line, "kernel/src/main.c", 14
L0049:	lda     #$3E
	jsr     _cputc
	.dbg	line, "kernel/src/main.c", 17
L0008:	jsr     _cgetc
	ldy     #$80
	sta     (sp),y
	.dbg	line, "kernel/src/main.c", 18
	cmp     #$08
	bne     L003F
	lda     sp
	ldx     sp+1
	jsr     _strdelc
	jsr     _cbkspc
	lda     #$00
	ldy     #$80
	sta     (sp),y
	bra     L0041
L003F:	lda     (sp),y
	jsr     _cputc
	.dbg	line, "kernel/src/main.c", 20
	ldy     #$80
L0041:	lda     (sp),y
	cmp     #$0D
	beq     L0042
	cmp     #$0A
	bne     L0047
	.dbg	line, "kernel/src/main.c", 21
L0042:	ldx     #$FF
	ldy     #$FF
L001E:	inx
	iny
	lda     (sp),y
	bne     L001E
	txa
	beq     L0044
	.dbg	line, "kernel/src/main.c", 22
	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #<(L0023)
	ldx     #>(L0023)
	jsr     _strcmp
	cpx     #$00
	bne     L0020
	cmp     #$00
	bne     L0020
	.dbg	line, "kernel/src/main.c", 23
	jsr     _cls
	.dbg	line, "kernel/src/main.c", 25
	bra     L0027
	.dbg	line, "kernel/src/main.c", 26
L0020:	lda     #<(L0029)
	ldx     #>(L0029)
	jsr     _cputs
	.dbg	line, "kernel/src/main.c", 31
L0027:	lda     #$00
L0044:	ldy     #$81
L0048:	sta     (sp),y
	cmp     #$80
	bcs     L0049
	lda     sp+1
	sta     ptr1+1
	lda     sp
	sta     ptr1
	lda     (sp),y
	tay
	lda     #$00
	sta     (ptr1),y
	ldy     #$81
	lda     (sp),y
	ina
	bra     L0048
	.dbg	line, "kernel/src/main.c", 35
L0047:	lda     (sp),y
	jsr     pusha
	lda     #$01
	jsr     leaa0sp
	jsr     _strcatc
	.dbg	line, "kernel/src/main.c", 16
	jmp     L0008
	.dbg	line

.endproc

